version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ .Branch }}-{{ checksum ".circleci/cache.lock" }}
      - run: 
          name: Install anypoint-cli
          command: |
            sudo npm install anypoint-cli;
      - run: 
          name: Install js-yaml
          command: |
            sudo npm install js-yaml;
      - run: 
        name: Create symbolic link for anypoint-cli
        command: | 
          sudo ln -s /home/circleci/project/node_modules/anypoint-cli/src/app.js /usr/local/bin/anypoint-cli;
      - save_cache:
          key: v1-npm-cache-{{ .Branch }}-{{ checksum ".circleci/cache.lock" }}
          paths:
            - node_modules
      - deploy:
          name: Deployment
          command: | 
            chmod +x .muleci/deployment.sh;
            .muleci/deployment.sh deployment_descriptor.yml;
